### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by sahilkur36** [adeb-deg/hysteresis-curve#1]
Not working for both of the hysteresis curves. See the files attached. Thank You

I am a newbie to Python. Please help me in this regard. Moreover, please add the functionality to obtain the backbone curve, too. Thank You.
[InputForceDisp.txt](https://github.com/user-attachments/files/16071985/InputForceDisp.txt)
[InputForceDisp1.txt](https://github.com/user-attachments/files/16071986/InputForceDisp1.txt)

**Comment by adeb-deg** [comment]
I have resolved the issue and added necessary information in the README file. Please let me know if the issue still persists

**Comment by sahilkur36** [comment]
Sir for this data its still not working. 
[InputForceDisp.txt](https://github.com/user-attachments/files/16247966/InputForceDisp.txt)
Please let me know if i have to change certain parameters. Thank you for your efforts and time

**Comment by adeb-deg** [comment]
It is working for me. Please let me know if you want to connect via Zoom and I can show you how to use it.

**Comment by adeb-deg** [comment]
Here is my code to run your Input data. 

```python
import numpy as np

fd = []
with open("InputForceDisp.txt", "r") as f:
	lines = f.readlines()
for line in lines:
	temp = line.strip().split(' ')
	temp = [float(item) for item in temp if len(item)]
	fd.append(temp)
fd = np.array(fd)

curve = HysteresisCurve(fd[:, 0], fd[:, 1], n_seg_env=4)

# first use hc.see_peaks_and_valleys(prominence=p) for different values of p to determine the adequate prominence
curve.see_peaks_and_valleys(prominence=0.55)
# then set
curve.prominence = 0.55
curve.plot()
curve.plot([20, 21], plot_env=True)

```
![fig6](https://github.com/user-attachments/assets/658dd5fe-26fb-4880-99ce-4cc8365434c2)
![fig7](https://github.com/user-attachments/assets/10d99602-6360-4903-b60a-dba9d55128e1)
![fig8](https://github.com/user-attachments/assets/9a471857-eb7f-472c-ad76-55ec41de7fc6)
